export const COMMANDS = {
  SYNC: 'SYNC',
  GROUP_STATUS: 'GROUP_STATUS',
  CREATE_TASK: 'CREATE_TASK',
  CREATE_TASKS: 'CREATE_TASKS',
  GET_TASK: 'GET_TASK',
  GET_TASKS: 'GET_TASKS',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASKS: 'DELETE_TASKS',
  PUBLISH_TASKS: 'PUBLISH_TASKS',
  UNPUBLISH_TASKS: 'UNPUBLISH_TASKS',
  QUEUE_START: 'QUEUE_START',
  QUEUE_STOP: 'QUEUE_STOP',
  QUEUE_CANCEL_TASK: 'QUEUE_CANCEL_TASK',
  QUEUE_CANCEL_TASKS: 'QUEUE_CANCEL_TASKS',
  QUEUE_CLEAR: 'QUEUE_CLEAR',
  GET_QUEUE_STATUS: 'GET_QUEUE_STATUS',
  SET_TASK_CONFIG: 'SET_TASK_CONFIG',
  RESET_TASKS: 'RESET_TASKS',
} as const;

export const DIRECT_COMMAND = {
  RUN_TASK: 'RUN_TASK',
  STOP_TASK: 'STOP_TASK',
  RETRY_TASK: 'RETRY_TASK',
  SKIP_TASK: 'SKIP_TASK',
  IS_TASK_RUNNING: 'IS_TASK_RUNNING',
} as const;

// export const TASK_COMMAND = {
//   CREATE_TASK: 'CREATE_TASK',
//   CREATE_TASKS: 'CREATE_TASKS',
//   DELETE_TASK: 'DELETE_TASK',
//   DELETE_TASKS: 'DELETE_TASKS',
//   UPDATE_TASK: 'UPDATE_TASK',
//   SYNC:""
// };

export type COMMANDS_TYPE = (typeof COMMANDS)[keyof typeof COMMANDS];
export type DIRECT_COMMAND_TYPE = (typeof DIRECT_COMMAND)[keyof typeof DIRECT_COMMAND];
// export type TASK_COMMAND_TYPE = (typeof TASK_COMMAND)[keyof typeof TASK_COMMAND];
